name: Deploy to WordPress.org
on:
  push:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]
jobs:
  tag:
    name: Deploy in SVN
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name:  Deploy
      run: |
        bash deploy.sh
    env:
      SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
      SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
      SVN_VERSION: '3.0.5'
      SVN_TEXT_COMMIT: 'test commit'