name: Deploy to WordPress.org
on:
  push:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]
jobs:
  tag:
    name: Deploy in SVN
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name:  Deploy
      run: |
        bash deploy.sh
    env:
      SVN_USE—ÉRNAME: 'calls'
      SVN_PASSWORD: 'calls123321'
